version: 2
project_name: marathon
builds:
  - goos:
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
dockers:
  - image_templates:
      - "ghcr.io/miketangoecho/{{.ProjectName}}:{{.Tag}}"
      - "ghcr.io/miketangoecho/{{.ProjectName}}:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url=https://github.com/miketangoecho/{{.ProjectName}}"
      - "--label=org.opencontainers.image.source=https://github.com/miketangoecho/{{.ProjectName}}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--build-arg=FFMPEG_VERSION={{.Env.FFMPEG_VERSION}}"